print('Good Morning \'Scientech Easy\'')

print("\n")
print("Welcome to \"Scientech Easy\"")
print("\n")
print("Welcome to\tScientech Easy")
print("\n")
print("1. Hello \'Python")
print("2. Hello \"Python")
print("3. Hello \tPython")
print("4. Hello \nPython")
print("5. Hello \rPython")
print("6. Hello \a Python")
print("7. Hello \\Python")
print("8. \ooo 20")
print("9. Hello \nPython")
print("10. Hello \bPython")
print("11. Hello \fPython")
print("12. Hello \vPython")
